
export const CategorieTypes = [
  "Web Development",
  "Science",
  "LifeStyle",
  "Movie",
  "Fashion",
  "Cars",
  "Pets",
  "Cultures",
  "Engineering",
  "Food",
  "Cuisins",
  "Photography",
  "Wild Life",
  "Bikes",
  "Sports",
  "Machines",
  "National Geography",
  "Anime",
  "Hentai",
  "Crypto",
  "Bitcoin",
  "Forbs",
  "Celebrities",
  "Data Science",
  "Self Improvement",
  "Writing",
  "Relationship",
  "Technologies",
  "Law",
  "Politics",
  "Productivity",
  "Other",
];